/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIComponents;

import PetGame.Game;
import PetGame.Pet;
import PetGame.PetDBConnection;
import PetGame.Player;
import javax.swing.ImageIcon;

/**
 *
 * @author wongk
 */
public class MainFrame extends javax.swing.JFrame {

    PetDBConnection pdb;
    Player player;
    Game game;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        pdb = new PetDBConnection();

        this.errorLabel.setVisible(false);

        this.newUsernameLabel.setVisible(false);
        this.newUserNameTextField.setVisible(false);
        this.newPasswordLabel.setVisible(false);
        this.newPasswordTextField.setVisible(false);
        this.newPetNameLabel.setVisible(false);
        this.newPetNameTextField.setVisible(false);
        this.newPetTypeLabel.setVisible(false);
        this.newPetTypeComboBox.setVisible(false);
        this.confirmButton.setVisible(false);

        if (!pdb.checkExistedTable("PetGame")) {
            pdb.createTable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameField = new javax.swing.JTextField();
        toyComboBox = new javax.swing.JComboBox<>();
        foodComboBox = new javax.swing.JComboBox<>();
        healthBar = new javax.swing.JProgressBar();
        hungerBar = new javax.swing.JProgressBar();
        energyBar = new javax.swing.JProgressBar();
        LoginButton = new javax.swing.JButton();
        buyFoodButton = new javax.swing.JButton();
        buyToyButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        happinessBar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        petImage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        newPetNameTextField = new javax.swing.JTextField();
        newUserNameTextField = new javax.swing.JTextField();
        newPetTypeComboBox = new javax.swing.JComboBox<>();
        newUsernameLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        newPetNameLabel = new javax.swing.JLabel();
        newPetTypeLabel = new javax.swing.JLabel();
        newPasswordTextField = new javax.swing.JPasswordField();
        endDayButton = new javax.swing.JButton();
        shopLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ball", "Doll", "Feather Toy", "Frisbee" }));
        toyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toyComboBoxActionPerformed(evt);
            }
        });

        foodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "Honey", "Spinach", "Steak" }));
        foodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodComboBoxActionPerformed(evt);
            }
        });

        healthBar.setForeground(new java.awt.Color(255, 51, 51));
        healthBar.setBorder(javax.swing.BorderFactory.createTitledBorder("Health"));

        hungerBar.setForeground(new java.awt.Color(102, 102, 0));
        hungerBar.setBorder(javax.swing.BorderFactory.createTitledBorder("Hunger"));

        energyBar.setForeground(new java.awt.Color(255, 255, 0));
        energyBar.setBorder(javax.swing.BorderFactory.createTitledBorder("Energy"));

        LoginButton.setText("Log in");
        LoginButton.setActionCommand("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        buyFoodButton.setText("Buy Food");
        buyFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyFoodButtonActionPerformed(evt);
            }
        });

        buyToyButton.setText("Buy Toy");
        buyToyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyToyButtonActionPerformed(evt);
            }
        });

        passwordField.setText("jPasswordField1");
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        happinessBar.setForeground(new java.awt.Color(51, 102, 255));
        happinessBar.setBorder(javax.swing.BorderFactory.createTitledBorder("Happiness"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Shop");

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");

        petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Blank.png"))); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Age: ");

        ageLabel.setText("000");

        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("Please enter a username and password");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        newPetNameTextField.setText("Enter Pet Name");

        newUserNameTextField.setText("Enter Username");

        newPetTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog", "Cat" }));

        newUsernameLabel.setText("Username:");

        newPasswordLabel.setText("Password:");

        newPetNameLabel.setText("Pet Name:");

        newPetTypeLabel.setText("Pet Type:");

        newPasswordTextField.setText("jPasswordField1");

        endDayButton.setText("End Day");
        endDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDayButtonActionPerformed(evt);
            }
        });

        shopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopLabel.setText("Buy an item");

        jLabel5.setText("Money:");

        moneyLabel.setText("$000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LoginButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(newGameButton))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(petImage)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(hungerBar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(healthBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(happinessBar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(energyBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ageLabel))))
                            .addComponent(errorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(buyFoodButton)
                                                        .addGap(29, 29, 29))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(foodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(toyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(buyToyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12))))
                                            .addComponent(shopLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(moneyLabel)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newUsernameLabel)
                                    .addComponent(newPasswordLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newUserNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newPetNameLabel)
                                    .addComponent(newPetTypeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newPetTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newPetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(confirmButton)
                                .addGap(80, 80, 80))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(endDayButton)
                .addGap(376, 376, 376))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(moneyLabel))
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(foodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(shopLabel)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buyToyButton)
                                    .addComponent(buyFoodButton)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(ageLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(healthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hungerBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)
                                    .addComponent(energyBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(happinessBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(petImage)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(endDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LoginButton)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newGameButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newUserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newUsernameLabel)
                            .addComponent(newPetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPetNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newPasswordLabel)
                            .addComponent(newPetTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPetTypeLabel)
                            .addComponent(confirmButton)
                            .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(exitButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toyComboBoxActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        if (this.usernameField == null || this.passwordField == null) {
            this.errorLabel.setVisible(true);
        } else {
            this.errorLabel.setVisible(false);
            if (pdb.checkUser(this.usernameField.getText(), String.valueOf(this.passwordField.getPassword()))) {
                String[] str = pdb.loginDB(this.usernameField.getText(), String.valueOf(this.passwordField.getPassword()));
                Pet pet = new Pet(str[0], Double.valueOf(str[3]), Double.valueOf(str[4]), Double.valueOf(str[5]), Double.valueOf(str[6]), Double.valueOf(str[7]), Double.valueOf(str[8]), Double.valueOf(str[9]), Double.valueOf(str[10]), Boolean.valueOf(str[11]));
                game.setPlayer(new Player(Double.valueOf(str[2]), pet));

                switch (str[1].toLowerCase()) {
                    case ("dog"):
                        this.petImage.setIcon(new ImageIcon("Dog.png"));
                        break;
                    case ("cat"):
                        this.petImage.setIcon(new ImageIcon("Cat.png"));
                        break;
                }
            } else {
                this.errorLabel.setVisible(true);
            }
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        this.newUsernameLabel.setVisible(true);
        this.newUserNameTextField.setVisible(true);
        this.newPasswordLabel.setVisible(true);
        this.newPasswordTextField.setVisible(true);
        this.newPetNameLabel.setVisible(true);
        this.newPetNameTextField.setVisible(true);
        this.newPetTypeLabel.setVisible(true);
        this.newPetTypeComboBox.setVisible(true);
        this.confirmButton.setVisible(true);
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        game.setPlayer(new Player(100, new Pet(this.newPetNameTextField.getText())));
        Pet pet = game.getPlayer().getPet();
        pdb.newUser(this.newUserNameTextField.getText().toLowerCase(), String.valueOf(this.newPasswordTextField.getPassword()).toLowerCase(), this.newPetTypeComboBox.getSelectedItem().toString(), this.newPetNameTextField.getText(), game.getPlayer().getMoney(), pet.getAge(), pet.getHealthLevel(), pet.getHungerLevel(), pet.getHappinessLevel(), pet.getEnergyLevel(), pet.getHungerDecay(), pet.getHappinessDecay(), pet.getEnergyDecay(), pet.getIsAlive());
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void endDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDayButtonActionPerformed
        this.healthBar.setValue((int) this.game.getPlayer().getPet().getHealthLevel());
        this.hungerBar.setValue((int) this.game.getPlayer().getPet().getHungerLevel());
        this.energyBar.setValue((int) this.game.getPlayer().getPet().getEnergyLevel());
        this.happinessBar.setValue((int) this.game.getPlayer().getPet().getHappinessLevel());
    }//GEN-LAST:event_endDayButtonActionPerformed

    private void buyFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyFoodButtonActionPerformed
        if (!game.feedPet(this.foodComboBox.getSelectedItem().toString().toLowerCase())) {
            this.shopLabel.setText("Not enough money to purchase item");
        }
        this.moneyLabel.setText("$" + this.game.getPlayer().getMoney());

    }//GEN-LAST:event_buyFoodButtonActionPerformed

    private void buyToyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyToyButtonActionPerformed
        if (!game.playPet(this.toyComboBox.getSelectedItem().toString().toLowerCase())) {
            this.shopLabel.setText("Not enough money to purchase item");
        }
        this.moneyLabel.setText("$" + this.game.getPlayer().getMoney());
    }//GEN-LAST:event_buyToyButtonActionPerformed

    private void foodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodComboBoxActionPerformed
        switch (this.foodComboBox.getSelectedItem().toString().toLowerCase()) {
            case ("apple"):
                this.shopLabel.setText(this.game.apple.toString());
                break;
            case ("honey"):
                this.shopLabel.setText(this.game.honey.toString());
                break;
            case ("spinach"):
                this.shopLabel.setText(this.game.spinach.toString());
                break;
            case ("steak"):
                this.shopLabel.setText(this.game.steak.toString());
                break;
        }
    }//GEN-LAST:event_foodComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton buyFoodButton;
    private javax.swing.JButton buyToyButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton endDayButton;
    private javax.swing.JProgressBar energyBar;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox<String> foodComboBox;
    private javax.swing.JProgressBar happinessBar;
    private javax.swing.JProgressBar healthBar;
    private javax.swing.JProgressBar hungerBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JButton newGameButton;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPasswordField newPasswordTextField;
    private javax.swing.JLabel newPetNameLabel;
    private javax.swing.JTextField newPetNameTextField;
    private javax.swing.JComboBox<String> newPetTypeComboBox;
    private javax.swing.JLabel newPetTypeLabel;
    private javax.swing.JTextField newUserNameTextField;
    private javax.swing.JLabel newUsernameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel petImage;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JComboBox<String> toyComboBox;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
